### ISSUE TITLE
Drive.getUrl is not raising exception when file is missing

### ISSUE THREAD

**Issue by yodosan** [adonisjs/drive#30]
## Prerequisites

According to the [documentation](https://docs.adonisjs.com/guides/drive#geturl), `Driver.getUrl` should raise an error if the file is missing, but it seems broken.
Trying using local and s3 drivers, the behavior is that even if the file is missing, getUrl is returning an URL, which leads to a 404.

## Package version
@adonisjs/core: 5.3.4
@adonisjs/driver-s3: 1.0.5

## Node.js and npm version
node: 14.17.1
npm 6.14.13

## Sample Code
Code is pretty straightforward.

Upload file:
```
await Drive.put(location, content)
```

Get URL file:
```
await Drive.getUrl(filename)
```

With `local` driver I'm getting: /uploads/b2786ed72a9faecbdd4c0d001163e095d7fd06d0b8b9bcf9b588e81863be1135

![image](https://user-images.githubusercontent.com/51509959/141951903-ea5b7af6-373d-4eaa-90e7-0dafce0d8d25.png)

With `s3` driver I'm getting: https://s3.eu-central-1.amazonaws.com/bucket-name-redacted/b2786ed72a9faecbdd4c0d001163e095d7fd06d0b8b9bcf9b588e81863be1135

![image](https://user-images.githubusercontent.com/51509959/141956409-192597d5-b31c-42dd-a637-6aed0cace3a0.png)

## Bonus
What I can add is that `Driver.get` is working as expected; in fact using this workaround I can "fix" the issue:

```
public async getUserProfilePicture(user: User): Promise<string | null> {
    const filename = user.encryptedEmail
    try {
        await Drive.get(filename)
        return Drive.getUrl(filename)
    } catch (e) {
        ctx.logger.info('Missing user profile picture')
        return null
    }
}
```

**Comment by Carassale** [comment]
@thetutlage Will this fix be present in the next release?
