### ISSUE TITLE
MakeUrl is deprecated

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/drive#38]
## Package version

2.0.9

## Node.js and npm version

14.15.5 and 7.23.0

## Sample Code (to reproduce the issue)

Use the method `getUrl` to print this message in the console 

```sh
(node:30252) You are using legacy the API of the "Route.makeUrl". We recommend reading the docs and use the latest API: DeprecationWarning
````

This is created in [this file](https://github.com/adonisjs/drive/blob/fe79a3302bc2bfb2fa7ed0e97548b4a241d9b84f/src/Drivers/Local.ts#L157) and reading the doc, the [new url builder must be used](https://docs.adonisjs.com/guides/routing#url-builder)

**Comment by thetutlage** [comment]
Can you please create a test that can help reproduce this issue? I am not able to have trigger warnings
