### ISSUE TITLE
getStream returns old `NodeJS.ReadableStream` interface instead of Readable instance

### ISSUE THREAD

**Issue by brkn** [adonisjs/drive#40]
## Package version
"@adonisjs/drive-gcs": "^1.0.4",

## Node.js and npm version
node v16.1.0
npm 7.11.2

## Sample Code

Try to get a stream.

```ts
const stream = await Drive.getStream("bucket/fileName")
// stream is NodeJS.ReadableStream instead of the newer `Readable`
```

More info on compatibility section here: https://nodejs.org/api/stream.html#compatibility-with-older-nodejs-versions

#### Workaround

Wrapping the stream. See:  https://nodejs.org/dist/latest-v16.x/docs/api/stream.html#readablewrapstream

**Comment by thetutlage** [comment]
Happy to accept the PR for the same :). Also, can you please check and see if same can be done for the https://github.com/adonisjs/drive-s3 and the https://github.com/adonisjs/drive-gcs drives as well?
