### ISSUE TITLE
The expected type comes from the 'driver' property, which is declared here in the 'LocalDriverConfig & { driver: "local" type; }'

### ISSUE THREAD

**Issue by LucasGeek** [adonisjs/drive#41]
## Package version
**2.2.0**

## Node.js and npm version
**Node.JS (16.13.1) | NPM (8.1.2)**

## Sample Code (to reproduce the issue)
I added S3 driver to the project with the command `npm i @adonisjs/drive-s3` and then I did its configuration with `node ace configure @adonisjs/drive-s3` but unfortunately the `driver: 's3'` is not found either generated again.

![bug](https://user-images.githubusercontent.com/33362579/171042039-82826271-8ae6-4b19-83a3-7f5f9e904229.png)

I don't know if it has any relationship, but this part of the code is missing the DriverContract and DriverConfig from s3 or another provider that I tested for the implementation of the drive

![drive_d_ts](https://user-images.githubusercontent.com/33362579/171044579-f815ad29-f0f6-4165-a9f0-875182bd56ce.png)

Configuration used.

![env_ts](https://user-images.githubusercontent.com/33362579/171043403-ec19ee6b-aa46-4830-9b3e-2bbd845ad839.png)
![package_json](https://user-images.githubusercontent.com/33362579/171043937-aa323566-07d8-44e6-8e40-4fc9e8729a90.png)

**Comment by thetutlage** [comment]
You need to fix the `contracts/drive.ts` file. Just replace its contents with the contents of this stub https://raw.githubusercontent.com/adonisjs/core/develop/templates/contracts/drive.txt

**Comment by momadthenomad** [comment]
Hello I'm getting the exact same issue with AdonisJS 5.9 but the linked solution above no longer works (broken link).
