### ISSUE TITLE
Can this be used as a standalone package (without adonisjs)?

### ISSUE THREAD

**Issue by FoxxMD** [adonisjs/drive#44]
I came here while looking at [flydrive](https://github.com/Slynova-Org/flydrive/issues/169).

Is it possible to use this package without adonisjs? Im in need of a storage abstraction library for another project but don't want (need) to integrate adonis into it (yet).

**Comment by thetutlage** [comment]
Nope. This one is coupled to AdonisJS.

**Comment by andresgutgon** [comment]
I understand is couple with AdonisJS but I'm curious what means the [standalone.ts](https://github.com/adonisjs/drive/blob/develop/standalone.ts) in this project
