### ISSUE TITLE
array push is not working after Drive.putStream()

### ISSUE THREAD

**Issue by msahidurr** [adonisjs/drive#50]
core version : "@adonisjs/core": "^5.8.6"

import { string } from '@ioc:Adonis/Core/Helpers'
import { createReadStream } from 'fs'
import { DateTime } from 'luxon'

let path : any[] = []
const fileStream = createReadStream(row.tmpPath!)
let fileName = string.camelCase(row.clientName).toLowerCase()
fileName = DateTime.now().toMillis() + "-" + fileName + "." + row.extname
await Drive.putStream(fileName, fileStream)

path.push({
     path: fileName
})

**Comment by targos** [comment]
I just tried in my project and could not reproduce. TBH it's highly unlikely that `putStream` would have a side-effect on arrays.

**Comment by MANTENN** [comment]
I ended up using the S3 sdk since my code never went past putStream. not sure why—no errors after it ran for 7000seconds.

```
const s3 = new S3({
  region: Env.get('S3_REGION'),
  secretAccessKey: Env.get('S3_SECRET'),
  accessKeyId: Env.get('S3_KEY'),
  maxRetries: 3,
})

      await request.multipart
        .onFile(
          'file',
          {
            size: '20mb',
            extnames: ['pdf', 'doc', 'docx'],
          },
          async (part) => {
            await s3
              .upload({
                Key:  part.filename,
                Bucket: Env.get('S3_BUCKET'),
                Body: part,
              })
              .promise()
          }
        )
        .process()
```
