### ISSUE TITLE
[Config] local basePath doesn't support full URL like https://example.com/

### ISSUE THREAD

**Issue by guoyunhe** [adonisjs/drive#52]
## Package version
2.3.0

## Node.js and npm version
18.16.0, pnpm 8.2.0

## Sample Code (to reproduce the issue)

I use `local` disk with basePath `https://example.com/storage`. Then I try to get URL:

```ts
const url = await Drive.getUrl('my-photo.png');
```

It returns:

```
/https://example.com/storage/my-photo.png
```

It should return:

```
https://example.com/storage/my-photo.png
```

**Comment by guoyunhe** [comment]
keep up

**Comment by guoyunhe** [comment]
keep up

**Comment by thetutlage** [comment]
Fixed with v6. The `fs` drive now accepts the `appUrl` to prefix the app domain https://docs.adonisjs.com/guides/digging-deeper/drive
