### ISSUE TITLE
MultipartFile helper’s moveToDisk method does not add writeOptions

### ISSUE THREAD

**Issue by kamilcglr** [adonisjs/drive#54]
### Package version

3.2.0

### Describe the bug

Hello,

**Context:**
I am using Adonis 6.14.0 with the drive plugin 3.2.0.
I am uploading a file and validating it with the included validator. 
I have a drive disk that is an S3 bucket.

When I try to move the file using the MultipartFile helper while providing the drive key and adding metadata for AWS, it seems that the metadata is being ignored. 

**Possible cause:**
I looked at the source code and it seems that when the `diskNameOrOptions` is provided, the `writeOptions` are ignored.(https://github.com/adonisjs/drive/blob/9478edad1eed3c81718c09e8ecabf004e1c2101d/providers/drive_provider.ts#L123-L135) 

Am I right ? 

Here is an example

```typescript
const metadata = {
          invoice_internal_reference_type: 'Autre',
          invoice_internal_reference: '',
          invoice_account_number: '',
          invoice_account_type: '',
          invoice_source_incident_caseid: '',
}
        
await payload.file.moveToDisk(
      `${new Date().getFullYear()}/${fileName}`,
      's3Drive',
      {
        Metadata: metadata,
      }
    )
```
    
But when I use the drive directly, it works. The metadata is passed to the AWS command and is visible in the bucket

```typescript
await drive
      .use('s3Drive')
     .moveFromFs(new URL(payload.file.tmpPath!, import.meta.url), `${new Date().getFullYear()}/${fileName}`, {
      Metadata: metadata,
      })
```

Thank you in advance.

**Comment by thetutlage** [comment]
Can you please run your application using `NODE_DEBUG="flydrive:*" npm run dev` and share the logs from the FlyDrive. Make sure to use the bodyparser API while debugging

**Comment by kamilcglr** [comment]
> Can you please run your application using `NODE_DEBUG="flydrive:*" npm run dev` and share the logs from the FlyDrive. Make sure to use the bodyparser API while debugging

Here are the logs 
```
FLYDRIVE:S3 68581: driver config {
  credentials: 'REDACTED',
  region: 'eu-west-1',
  bucket: 'my-s3-bucket',
  visibility: 'private'
}
FLYDRIVE:CORE 68581: creating disk instance for service s3Drive
FLYDRIVE:S3 68581: creating/updating file my-s3-bucket:invoicesFromSupplier/2024/1234_f3e1ea6c-8565-4f56-bbb6-722a939f1d00.pdf
FLYDRIVE:S3 68581: setting "invoicesFromSupplier/2024/1234_f3e1ea6c-8565-4f56-bbb6-722a939f1d00.pdf" file's content-type to "application/pdf"
FLYDRIVE:S3 68581: s3 write options {
  Bucket: 'my-s3-bucket',
  ACL: 'private',
  ContentType: 'application/pdf'
}

```

**Comment by thetutlage** [comment]
Ohh yes. I see there is an error with the logic of using options. Can you please create a PR with the fix?
